/**
 * PDF Worker Thread
 * 
 * Runs pdfkit generation in an isolated thread to avoid blocking
 * the main NestJS event loop. Used for heavy PDF operations.
 * 
 * Workflow:
 * 1. PdfService calls runInWorker(jobType, data)
 * 2. Worker receives message via parentPort
 * 3. Worker generates PDF buffer using pdfkit
 * 4. Worker posts buffer back to main thread
 * 5. PdfService receives buffer and pipes to HTTP response
 */

const { parentPort } = require('worker_threads');
const PDFDocument = require('pdfkit');

if (!parentPort) {
    throw new Error('This file must be run as a worker thread');
}

parentPort.on('message', async (job: { type: string; data: any }) => {
    try {
        let buffer: Buffer;

        switch (job.type) {
            case 'invoice':
                buffer = await generateInvoicePdf(job.data);
                break;
            case 'sales-report':
                buffer = await generateSalesReportPdf(job.data);
                break;
            default:
                throw new Error(`Unknown job type: ${job.type}`);
        }

        parentPort!.postMessage({ success: true, buffer });
    } catch (error: any) {
        parentPort!.postMessage({ success: false, error: error.message });
    }
});

/**
 * Generate invoice PDF buffer
 */
function generateInvoicePdf(data: any): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on('data', (chunk: Buffer) => buffers.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', (err: Error) => reject(err));

        // Header
        doc.fontSize(18).text(data.tenantName || 'OTOHUB', { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(14).text('INVOICE', { align: 'center' });
        doc.moveDown();

        // Invoice details
        if (data.invoiceNumber) {
            doc.fontSize(10).text(`No. Invoice: ${data.invoiceNumber}`);
        }
        doc.text(`Tanggal: ${data.date || new Date().toLocaleDateString('id-ID')}`);
        doc.moveDown();

        // Customer info
        if (data.customerName) {
            doc.text(`Kepada: ${data.customerName}`);
            if (data.customerPhone) doc.text(`Telp: ${data.customerPhone}`);
            doc.moveDown();
        }

        // Vehicle info
        if (data.vehicleName) {
            doc.text(`Kendaraan: ${data.vehicleName}`);
            if (data.licensePlate) doc.text(`Plat: ${data.licensePlate}`);
            doc.moveDown();
        }

        // Price
        if (data.finalPrice) {
            doc.fontSize(12).text(`Total: ${data.finalPrice}`, { align: 'right' });
        }

        doc.moveDown(2);
        doc.fontSize(8).text(`Generated by OTOHUB Worker on ${new Date().toLocaleString('id-ID')}`, {
            align: 'center',
        });

        doc.end();
    });
}

/**
 * Generate sales report PDF buffer
 */
function generateSalesReportPdf(data: any): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on('data', (chunk: Buffer) => buffers.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', (err: Error) => reject(err));

        // Header
        doc.fontSize(18).text(data.tenantName || 'OTOHUB', { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(14).text('LAPORAN PENJUALAN', { align: 'center' });
        doc.moveDown();

        // Summary
        doc.fontSize(10);
        doc.text(`Periode: ${data.period || 'N/A'}`);
        doc.text(`Total Transaksi: ${data.totalCount || 0}`);
        doc.text(`Total Revenue: ${data.totalRevenue || 'Rp 0'}`);
        doc.moveDown();

        // Transaction list
        if (data.transactions && Array.isArray(data.transactions)) {
            for (const tx of data.transactions) {
                doc.text(`• ${tx.date} — ${tx.vehicle} — ${tx.price}`, { indent: 10 });
            }
        }

        doc.moveDown(2);
        doc.fontSize(8).text(`Generated by OTOHUB Worker on ${new Date().toLocaleString('id-ID')}`, {
            align: 'center',
        });

        doc.end();
    });
}
